criterium/urls.py
from django.urls import path
from .views import (RaceDetailView, RaceRedirectView, CorrectRedirectView,
    RaceListView, RaceListAthleteView)

app_name = 'criterium'
urlpatterns = [
    path('', RaceRedirectView.as_view(), name = 'all_editions'),
    path('<int:year>/', CorrectRedirectView.as_view(), name = 'correct_edition'),
    path('<int:year>-<int:year2>/', RaceListView.as_view(), name = 'edition'),
    path('<int:year>-<int:year2>/athlete/<int:id>',
        RaceListAthleteView.as_view(), name = 'athlete'),
    path('<int:year>-<int:year2>/<slug>/', RaceDetailView.as_view(), name = 'race'),
    ]

users/urls.py
from django.urls import path
from .views import (FrontLoginView, FrontLogoutView, FrontPasswordResetView,
    TemplateResetView, FrontPasswordResetConfirmView, TemplateResetDoneView,
    TemplateAccountView, FrontPasswordChangeView, FrontPasswordChangeDoneView,
    ProfileChangeView, ProfileDeleteView, TemplateDeletedView,
    ProfileChangeRegistryView, ProfileChangeAddressView, ProfileChangeCourseView,
    ProfileChangeNoCourseView, ProfileAddChildView, ProfileDeleteChildView,
    TemplateDeletedChildView, ProfileReleaseView, TemplateReleasedView)

#namespace is '/accounts/'
urlpatterns = [
    path('profile/', TemplateAccountView.as_view(),
        name='profile'),
    path('profile/<int:pk>/change/', ProfileChangeView.as_view(),
        name='profile_change'),
    path('profile/<int:pk>/change/registry/', ProfileChangeRegistryView.as_view(),
        name='profile_change_registry'),
    path('profile/<int:pk>/change/address/', ProfileChangeAddressView.as_view(),
        name='profile_change_address'),
    path('profile/<int:pk>/change/course/', ProfileChangeCourseView.as_view(),
        name='profile_change_course'),
    path('profile/<int:pk>/change/no_course/', ProfileChangeNoCourseView.as_view(),
        name='profile_change_no_course'),
    path('profile/add_child/', ProfileAddChildView.as_view(),
        name='profile_add_child'),
    path('profile/<int:pk>/delete/', ProfileDeleteView.as_view(),
        name='profile_delete'),
    path('profile/<int:pk>/delete_child/', ProfileDeleteChildView.as_view(),
        name='profile_delete_child'),
    path('profile/deleted/', TemplateDeletedView.as_view(),
        name='profile_deleted'),
    path('profile/deleted_child/', TemplateDeletedChildView.as_view(),
        name='profile_deleted_child'),
    path('profile/<int:pk>/release/', ProfileReleaseView.as_view(),
        name='profile_release'),
    path('profile/released/', TemplateReleasedView.as_view(),
        name='profile_released'),
    path('login/', FrontLoginView.as_view(),
        name='front_login'),
    path('logout/', FrontLogoutView.as_view(),
        name='front_logout'),
    path('password_reset/', FrontPasswordResetView.as_view(),
        name='front_password_reset'),
    path('password_reset/done/', TemplateResetView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', FrontPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', TemplateResetDoneView.as_view(),
        name='password_reset_complete'),
    path('password_change/', FrontPasswordChangeView.as_view(),
        name='password_change'),
    path('password_change_done/', FrontPasswordChangeDoneView.as_view(),
        name='password_change_done'),
    ]

criterium/models.py
from datetime import datetime

from django.db import models
from django.contrib.postgres.fields import JSONField

from users.models import User
from cronache.models import Event, Location
from project.utils import generate_unique_slug

from .choices import *

class Race(models.Model):
    title = models.CharField('Nome', help_text="Il nome della gara",
        max_length = 50)
    slug = models.SlugField(max_length=50, editable=False, null=True)
    event = models.ForeignKey(Event, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = 'Evento',
        related_name = 'event_race')
    date = models.DateField('Data', blank= True, null=True,
        help_text="In mancanza di Evento", )
    location = models.ForeignKey(Location, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = 'Luogo',
        help_text="In mancanza di Evento", )
    type = models.CharField('Tipo', choices = TYPE, max_length = 4,
        blank= True, null=True, )
    description = models.CharField('Descrizione', blank= True, null=True,
        max_length = 500)

    def get_date(self):
        if self.event:
            return self.event.date.date()
        return self.date
    get_date.short_description = 'Data'

    def get_edition(self):
        date = self.get_date()
        year = date.year
        month = date.month
        if month >= 11:
            return str(year) + '-' + str(year+1)
        else:
            return str(year-1) + '-' + str(year)
    get_edition.short_description = 'Edizione'

    def get_path(self):
        return '/criterium/' + self.get_edition() + '/' + self.slug

    def get_location(self):
        if self.event:
            return self.event.location
        return self.location
    get_location.short_description = 'Luogo'

    def save(self, *args, **kwargs):
        if not self.slug:  # create
            self.slug = generate_unique_slug(Race, self.title)
        if not self.date:
            temp = self.event.date
            #conditional added for test to work
            if isinstance(temp, str):
                temp = temp.split(' ')[0]
                self.date = datetime.strptime(temp, '%Y-%m-%d')
            else:
                self.date = temp.date()
        super(Race, self).save(*args, **kwargs)
        RaceCache.objects.get_or_create(race_id = self.id)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Gara'
        verbose_name_plural = 'Gare'
        ordering = ('-date', )

class RaceCache(models.Model):
    race= models.OneToOneField(Race, on_delete=models.CASCADE,
        primary_key=True)
    cache = JSONField(null=True)

class AthleteManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('user__last_name',
            'user__first_name')

class Athlete(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
        verbose_name = 'Iscritto', null = True, )
    race = models.ForeignKey(Race, on_delete=models.CASCADE,
        editable = False, null = True, )
    points = models.IntegerField('Punti')
    placement = models.IntegerField('Piazzamento assoluto', blank = True,
        null = True, )
    time = models.TimeField('Tempo', blank = True, null = True, )

    objects = AthleteManager()

    def __str__(self):
        return self.user.get_full_name()

    def get_full_name(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'Atleta'
        verbose_name_plural = 'Atleti/e'

criterium/forms.py
from django import forms
from django.forms import ModelForm
from .models import Race, Athlete
from cronache.models import Event
from users.models import User

class RaceForm(ModelForm):
    event = forms.ModelChoiceField(label="Evento", required = False,
        queryset = Event.objects.filter(tags__name__in = ['criterium',
        'Criterium'], ), )

    def clean_date(self):
        date = self.cleaned_data['date']
        event = self.cleaned_data['event']
        if not date and not event:
            msg = 'Senza evento occorre inserire almeno la data.'
            raise forms.ValidationError(msg, code='no_date')
        return date

    class Meta:
        model = Race
        fields = '__all__'

class AthleteForm(ModelForm):
    user = forms.ModelChoiceField(label="Iscritto", required = True,
        queryset = User.objects.filter(profile__parent = None,
            profile__sector__in = ['1-YC', '2-NC'],
            is_active = True ).order_by('last_name', 'first_name'), )

    class Meta:
        model = Athlete
        fields = '__all__'

criterium/views.py
from datetime import datetime

from django.shortcuts import get_object_or_404
from django.http import Http404
from django.views.generic import (DetailView, RedirectView, ListView)

from .models import (Race, Athlete, )
from users.models import User

class RaceDetailView(DetailView):
    model = Race
    context_object_name = 'race'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        race = context['object']
        edition = race.get_edition()
        if edition != str(self.kwargs['year'])+'-'+str(self.kwargs['year2']):
            raise Http404("Wrong edition")
        athletes = Athlete.objects.filter(race_id=race.id)
        females = athletes.filter(user__profile__gender='F').order_by('-points',
            'placement', 'user__last_name', 'user__first_name')
        males = athletes.filter(user__profile__gender='M').order_by('-points',
            'placement', 'user__last_name', 'user__first_name')
        context['females'] = females
        context['males'] = males
        return context

class RaceListMixin:

    def get_queryset(self):
        year1 = self.kwargs['year']
        year2 = self.kwargs['year2']
        if year2 != year1+1:
            raise Http404("Edition years are not consecutive")
        qs = Race.objects.filter(date__gte = datetime(year1, 11, 1),
            date__lt = datetime(year2, 11, 1)).order_by('date')
        return qs

    def get_status(self, year):
        if datetime(year, 10, 31) > datetime.now():
            return 'provvisoria'
        return 'definitiva'

    def get_context_years(self, context):
        context['year']= self.kwargs['year']
        context['year2']= self.kwargs['year2']
        context['year0'] = context['year'] - 1
        context['year3'] = context['year2'] + 1
        context['status'] = self.get_status(context['year2'])
        return context

class RaceListAthleteView(RaceListMixin, ListView):
    model = Race
    ordering = ('date', )
    context_object_name = 'all_races'
    template_name = 'criterium/race_list_athlete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.get_context_years(context)
        user = get_object_or_404(User, id=self.kwargs['id'])
        context['name'] = user.get_full_name()
        context['id'] = user.id
        race_list = context['all_races'].values_list('id', flat = True)
        athletes = Athlete.objects.filter(race_id__in = race_list,
            user_id = context['id'])
        if athletes:
            first = athletes.first()
            race_dict = {}
            for race in context['all_races']:
                try:
                    athlete = athletes.get(race_id = race.id )
                    race_dict[race] = athlete.points
                except:
                    pass
            context['all_races'] = race_dict
        else:
            context['all_races'] = None
        return context

class RaceListView(RaceListMixin, ListView):
    model = Race
    ordering = ('date', )
    context_object_name = 'all_races'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.get_context_years(context)
        athl_list = []
        name_dict = {}
        fem_sums = {}
        male_sums = {}
        #get all athlete lists from race caches
        for race in context['all_races']:
            athl_list.extend(race.racecache.cache)
        #initialize point sums for each athlete
        for athl in athl_list:
            name_dict[athl['user']] = athl['name']
            if athl['gender'] == 'F':
                fem_sums[athl['user']] = 0
            else:
                male_sums[athl['user']] = 0
        #adding points to point sums
        for athl in athl_list:
            if athl['gender'] == 'F':
                fem_sums[athl['user']] += athl['points']
            else:
                male_sums[athl['user']] += athl['points']
        # thanks to https://stackoverflow.com/questions/613183/
        # how-do-i-sort-a-dictionary-by-value
        fem_sums = {k: v for k, v in sorted(fem_sums.items(),
            key=lambda item: item[1], reverse = True)}
        male_sums = {k: v for k, v in sorted(male_sums.items(),
            key=lambda item: item[1], reverse = True)}
        #adding names
        for id, point_sum in fem_sums.items():
            fem_sums[id] = (name_dict[id], point_sum)
        for id, point_sum in male_sums.items():
            male_sums[id] = (name_dict[id], point_sum)
        context['females'] = fem_sums
        context['males'] = male_sums
        return context

def get_edition_years():
    date = datetime.now()
    year = date.year
    month = date.month
    if month >= 11:
        year1 = year
        year2 = year + 1
    else:
        year1 = year - 1
        year2 = year
    return year1, year2

class RaceRedirectView(RedirectView):
    """redirects simple /criterium/ url to current edition url"""
    def get_redirect_url(self, *args, **kwargs):
        year1, year2 = get_edition_years()
        url = f'/criterium/{year1}-{year2}/'
        return url

class CorrectRedirectView(RedirectView):
    """redirects simple year url to double year url"""
    def get_redirect_url(self, *args, **kwargs):
        year = kwargs['year']
        url = f'/criterium/{year}-{year+1}/'
        return url

criterium/templates/criterium/race_detail.html
{% extends 'base.html' %}

{% block title %}RP | {{ race.title }}{%endblock title %}
{% block content %}
<div class="row row-striped">
  <div class="col-md-2 text-right">
    <i class="fa fa-flag-checkered fa-3x" aria-hidden="true"></i>
    <a href="/criterium/{{ race.get_edition }}/"><h4>{{ race.get_edition }}</h4></a>
  </div>
  <div class="col-md-10">
    <h3 class="text-uppercase"><strong>{{ race.title }}</strong></h3>
    <ul class="list-inline">
      <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ race.get_date }}</li>
      {% if race.type %}
        <li class="list-inline-item"><i class="fa fa-wheelchair-alt" aria-hidden="true"></i> {{ race.get_type_display }}</li>
      {% endif %}
      {% if race.location %}
      <li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i>
        <a href="/luoghi/{{ race.get_location.slug }}">{{ race.get_location }}</a>
      </li>
      {% endif %}
      {% if race.event %}
        <li class="list-inline-item"><i class="fa fa-link" aria-hidden="true"></i>
        <a href="{{ race.event.get_path }}">{{ race.event.title }}</a></li>
      {% endif %}
      {% if perms.criterium.change_race %}
      <li class="list-inline-item">
        <i class="fa fa-pencil" aria-hidden="true"></i>
        <a href="/admin/criterium/race/{{ race.id }}/change/">Modifica</a>
      </li>
      {% endif %}
    </ul>
    <p>{{ race.description }}</p>
  </div>
</div>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    {% if females %}
    <h4>Classifica femminile</h4>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Punti</th>
            <th scope="col">Piazzamento</th>
            <th scope="col">Tempo</th>
          </tr>
        </thead>
        <tbody>
          {% for female in females %}
          <tr>
            <td>{{ female.user.get_full_name }}</td>
            <td>{{ female.points }}</td>
            <td>{{ female.placement|default_if_none:"--" }}</td>
            <td>{{ female.time|time:"H:i:s" }}</td>
          </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
    {% endif %}
    {% if males %}
    <h4>Classifica maschile</h4>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead class="thead-light">
          <tr>
            <th scope="col">Nome</th>
            <th scope="col">Punti</th>
            <th scope="col">Piazzamento</th>
            <th scope="col">Tempo</th>
          </tr>
        </thead>
        <tbody>
          {% for male in males %}
          <tr>
            <td>{{ male.user.get_full_name }}</td>
            <td>{{ male.points }}</td>
            <td>{{ male.placement|default_if_none:"--" }}</td>
            <td>{{ male.time|time:"H:i:s" }}</td>
          </tr>
          {% endfor %}
        <tbody>
      </table>
    </div>
    {% endif %}
  </div>
</div>
{% endblock content %}

criterium/templates/criterium/race_list.html
{% extends 'base.html' %}

{% block title %}RP | Criterium {{ year }}-{{ year2 }}{% endblock title %}
{% block content %}
<h4><strong>Criterium edizione {{ year }}-{{ year2 }}</strong></h4>
<hr class="mb-4">
{% if all_races %}
  <h4>Lista delle gare</h4>
  <ul>
  {% for race in all_races %}
    <li>
      <a href="{{ race.get_path }}">{{ race.title }}, </a>
      {{ race.date|date:"d M Y"}},
      {% if race.location %}
        {{ race.get_location }}
      {% endif %}
      {% if race.event %}
        <a href="{{ race.event.get_path }}">(leggi la cronaca)</a>
      {% endif %}
    </li>
  {% endfor %}
  </ul>
  {% if females %}
  <h5>Classifica femminile {{ status }}</h5>
    <ol>
    {% for id, points in females.items %}
      <li>
        <a href="/criterium/{{ year }}-{{ year2 }}/athlete/{{ id }}">{{ points.0 }}</a>,
        {{ points.1 }}
      </li>
    {% endfor %}
    </ol>
  {% endif %}
  {% if males %}
  <h5>Classifica maschile {{ status }}</h5>
    <ol>
    {% for id, points in males.items %}
      <li>
        <a href="/criterium/{{ year }}-{{ year2 }}/athlete/{{ id }}">{{ points.0 }}</a>,
        {{ points.1 }}
      </li>
    {% endfor %}
    </ol>
  {% endif %}
{% else %}
    <div class="col-md-12">
        <p>Non sono registrate gare in questa edizione.</p>
    </div>
{% endif %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    <li><a href="/criterium/{{ year0 }}-{{ year }}/" class="page-link">&laquo; PRECEDENTE </a></li>
    <li><a href="/criterium/{{ year2 }}-{{ year3 }}/" class="page-link"> SUCCESSIVA &raquo;</a></li>
  </ul>
  </nav>
{% endblock content %}

criterium/templates/criterium/race_list_athlete.html
{% extends 'base.html' %}

{% block title %}RP | Criterium {{ year }}-{{ year2 }} | {{ name }}{% endblock title %}
{% block content %}
<h4><strong>Criterium edizione
  <a href="/criterium/{{ year }}-{{ year2 }}/">{{ year }}-{{ year2 }}</a>
  per l'atleta {{ name }}</strong></h4>
<hr class="mb-4">
{% if all_races %}
  <h4>Lista {{ status }} delle gare</h4>
  <ul>
  {% for race, points in all_races.items %}
    <li>
      <a href="{{ race.get_path }}">{{ race.title }}, </a>
      {{ points }} punti
    </li>
  {% endfor %}
  </ul>
{% else %}
    <div class="col-md-12">
        <p>Non sono registrate gare in questa edizione per questo atleta.</p>
    </div>
{% endif %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    <li><a href="/criterium/{{ year0 }}-{{ year }}/athlete/{{ id }}" class="page-link">&laquo; PRECEDENTE </a></li>
    <li><a href="/criterium/{{ year2 }}-{{ year3 }}/athlete/{{ id }}" class="page-link"> SUCCESSIVA &raquo;</a></li>
  </ul>
  </nav>
{% endblock content %}