users/urls.py
from django.urls import path
from .views import (FrontLoginView, FrontLogoutView, FrontPasswordResetView,
    TemplateResetView, FrontPasswordResetConfirmView, TemplateResetDoneView,
    TemplateAccountView, FrontPasswordChangeView, FrontPasswordChangeDoneView,
    ProfileChangeView, ProfileDeleteView, TemplateDeletedView,
    ProfileChangeRegistryView, ProfileChangeAddressView, ProfileChangeCourseView,
    ProfileChangeNoCourseView, ProfileAddChildView, ProfileDeleteChildView,
    TemplateDeletedChildView, ProfileReleaseView, TemplateReleasedView)

#namespace is '/accounts/'
urlpatterns = [
    path('profile/', TemplateAccountView.as_view(),
        name='profile'),
    path('profile/<int:pk>/change/', ProfileChangeView.as_view(),
        name='profile_change'),
    path('profile/<int:pk>/change/registry/', ProfileChangeRegistryView.as_view(),
        name='profile_change_registry'),
    path('profile/<int:pk>/change/address/', ProfileChangeAddressView.as_view(),
        name='profile_change_address'),
    path('profile/<int:pk>/change/course/', ProfileChangeCourseView.as_view(),
        name='profile_change_course'),
    path('profile/<int:pk>/change/no_course/', ProfileChangeNoCourseView.as_view(),
        name='profile_change_no_course'),
    path('profile/add_child/', ProfileAddChildView.as_view(),
        name='profile_add_child'),
    path('profile/<int:pk>/delete/', ProfileDeleteView.as_view(),
        name='profile_delete'),
    path('profile/<int:pk>/delete_child/', ProfileDeleteChildView.as_view(),
        name='profile_delete_child'),
    path('profile/deleted/', TemplateDeletedView.as_view(),
        name='profile_deleted'),
    path('profile/deleted_child/', TemplateDeletedChildView.as_view(),
        name='profile_deleted_child'),
    path('profile/<int:pk>/release/', ProfileReleaseView.as_view(),
        name='profile_release'),
    path('profile/released/', TemplateReleasedView.as_view(),
        name='profile_released'),
    path('login/', FrontLoginView.as_view(),
        name='front_login'),
    path('logout/', FrontLogoutView.as_view(),
        name='front_logout'),
    path('password_reset/', FrontPasswordResetView.as_view(),
        name='front_password_reset'),
    path('password_reset/done/', TemplateResetView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', FrontPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', TemplateResetDoneView.as_view(),
        name='password_reset_complete'),
    path('password_change/', FrontPasswordChangeView.as_view(),
        name='password_change'),
    path('password_change_done/', FrontPasswordChangeDoneView.as_view(),
        name='password_change_done'),
    ]

blog/models.py
from datetime import datetime

from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.utils.timezone import now
from django.utils.html import strip_tags

from taggit.managers import TaggableManager

from project.utils import generate_unique_slug
from streamfield.fields import StreamField
from streamblocks.models import (IndexedParagraph, CaptionedImage, Gallery,
    LandscapeGallery, DownloadableFile, LinkableList, BoxedText, HomeButton)
from users.models import User
from cronache.models import Event
from .choices import *

class Article(models.Model):
    carousel = StreamField(model_list=[ LandscapeGallery, ],
        null=True, blank=True, verbose_name="Galleria",
        help_text="Una sola galleria, per favore, larghezza minima immagini 2048px")
    title = models.CharField('Titolo',
        help_text="Il titolo dell'articolo",
        max_length = 50)
    slug = models.SlugField(max_length=50, editable=False, null=True)
    date = models.DateTimeField('Data', default = now, )
    last_updated = models.DateTimeField(editable=False, null=True)
    intro = models.CharField('Introduzione',
        default = 'Un altro articolo di approfondimento!', max_length = 100)
    stream = StreamField( model_list=[ IndexedParagraph, CaptionedImage,
            Gallery, DownloadableFile, LinkableList, BoxedText],
            verbose_name="Testo" )
    stream_search = models.TextField(editable=False, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = 'Autore')
    tags = TaggableManager(verbose_name="Categorie",
        help_text="Lista di categorie separate da virgole",
        through=None, blank=True)
    notice = models.CharField(max_length = 4, choices = NOTICE,
        blank = True, null = True, verbose_name = 'Notifica via email',
        help_text = """Invia notifica in automatico selezionando
            'Invia notifica' e salvando l'articolo.
            """)

    def get_image(self):
        image = None
        gallery_list = self.carousel.from_json()
        if gallery_list:
            gallery = gallery_list[0]
            image = LandscapeGallery.objects.filter( id__in = gallery['id'] ).first()
        if image:
            return image.fb_image
        return

    def get_path(self):
        temp = self.date
        #conditional added for test to work
        if isinstance(temp, str):
            temp = temp.split(' ')[0]
            temp = datetime.strptime(temp, '%Y-%m-%d')
        return '/articoli/' + temp.strftime("%Y/%m/%d") + '/' + self.slug

    def get_uploads(self):
        return UserUpload.objects.filter(post_id=self.id)

    def get_tags(self):
        return list(self.tags.names())

    def get_previous(self):
        try:
            return self.get_previous_by_date()
        except Article.DoesNotExist:
            return

    def get_next(self):
        try:
            return self.get_next_by_date()
        except Article.DoesNotExist:
            return

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(Article, self.title)
        self.last_updated = now()
        #in tests treats stream as str instead of StreamField object
        #probably should use transaction instaed
        #but for now this patch works
        if isinstance(self.stream, str):
            from streamfield.base import StreamObject
            tmp = StreamObject( value = self.stream,
                model_list=[ IndexedParagraph, CaptionedImage,
                    Gallery, DownloadableFile, LinkableList, BoxedText ], )
            self.stream_search = strip_tags(tmp.render)
        else:
            self.stream_search = strip_tags(self.stream.render)
        if self.notice == 'SPAM':
            message = self.title + '\n'
            message += self.intro + '\n'
            url = settings.BASE_URL + self.get_path()
            message += 'Fai click su questo link per leggerlo: ' + url + '\n'
            recipients = User.objects.filter( is_active = True, )
            #inactive users may not have profile
            recipients = recipients.filter( profile__yes_spam = True, )
            mailto = []
            for recipient in recipients:
                mailto.append(recipient.email)
            subject = f'Nuovo articolo su {settings.WEBSITE_NAME}'
            email = EmailMessage(subject, message, settings.SERVER_EMAIL,
                mailto)
            email.send()
            self.notice = 'DONE'
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Articolo'
        verbose_name_plural = 'Articoli'
        ordering = ('-date', )

class UserUpload(models.Model):
    event = models.ForeignKey(Event, on_delete = models.CASCADE,
        null = True, related_name='event_uploads')
    post = models.ForeignKey(Article, on_delete = models.CASCADE,
        null = True, related_name='article_uploads')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null = True,
        verbose_name = 'Utente')
    date = models.DateTimeField('Data', default = now, )
    image = models.ImageField('Immagine', blank = True, null = True,
        upload_to = 'uploads/articles/users/',)
    body = models.TextField('Testo', help_text = "Scrivi qualcosa.", )

    def __str__(self):
        return 'Contributo - ' + str(self.id)

    class Meta:
        verbose_name = 'Contributo'
        verbose_name_plural = 'Contributi'
        ordering = ('-id', )

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import UserUpload, Article
from users.models import User

class UserUploadForm(ModelForm):
    body = forms.CharField(label = 'Testo',
        widget=forms.Textarea(attrs={'placeholder': "Scrivi qui il messaggio"}))
    class Meta:
        model = UserUpload
        fields = ('image', 'body',)

class ArticleForm(ModelForm):
    author = forms.ModelChoiceField(label="Autore", required = False,
        queryset = User.objects.with_perm('blog.view_article'), )

    class Meta:
        model = Article
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (ListView, DetailView, CreateView,
    TemplateView)
from django.views.generic.dates import (ArchiveIndexView, YearArchiveView,
    MonthArchiveView, DayArchiveView, )
from taggit.models import Tag

from users.models import User
from cronache.models import Event

from .forms import UserUploadForm
from .models import (UserUpload, Article,)

class TagMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        if 'tag' in self.request.GET:
            context['tag_filter'] = self.request.GET['tag']
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if 'tag' in self.request.GET:
            qs = qs.filter(tags__name=self.request.GET['tag'])
        return qs

class ArticleArchiveIndexView(TagMixin, ArchiveIndexView):
    model = Article
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    paginate_by = 12
    allow_empty = True

class ArticleYearArchiveView(TagMixin, YearArchiveView):
    model = Article
    make_object_list = True
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    paginate_by = 12
    year_format = '%Y'
    allow_empty = True

class ArticleMonthArchiveView(TagMixin, MonthArchiveView):
    model = Article
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    year_format = '%Y'
    month_format = '%m'
    allow_empty = True

class ArticleDayArchiveView(TagMixin, DayArchiveView):
    model = Article
    date_field = 'date'
    allow_future = True
    context_object_name = 'posts'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    allow_empty = True

class DetailArticle(DetailView):
    model = Article
    context_object_name = 'post'
    slug_field = 'slug'

class UserUploadCreateView(LoginRequiredMixin, CreateView):
    model = UserUpload
    form_class = UserUploadForm

    def get(self, request, *args, **kwargs):
        usr = self.request.user
        if not usr.profile.is_trusted:
            raise Http404("User is not trusted")
        return super(UserUploadCreateView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        if 'event_id' in self.request.GET:
            evt = Event.objects.get(id=self.request.GET['event_id'])
            return evt.get_path() + '/#upload-anchor'
        elif 'post_id' in self.request.GET:
            pst = Article.objects.get(id=self.request.GET['post_id'])
            return pst.get_path() + '/#upload-anchor'
        return super(UserUploadCreateView, self).get_success_url(self)

    def form_valid(self, form):
        form.instance.user = self.request.user
        if 'event_id' in self.request.GET:
            form.instance.event = Event.objects.get(id=self.request.GET['event_id'])
        elif 'post_id' in self.request.GET:
            form.instance.post = Article.objects.get(id=self.request.GET['post_id'])
        return super().form_valid(form)

class AuthorListView(ListView):
    model = User
    #context_object_name = 'authors'
    template_name = 'blog/author_list.html'
    paginate_by = 10
    allow_empty = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_users = context['user_list']
        all_articles = Article.objects.all()
        all_contrib = UserUpload.objects.all()
        author_dict = {}
        for author in all_users:
            art_count = all_articles.filter(author_id = author.id).count()
            contrib_count = all_contrib.filter(user_id = author.id).count()
            if art_count or contrib_count:
                author_dict[author]=(art_count, contrib_count)
        context['authors'] = author_dict
        return context

class ByAuthorListView(ListView):
    model = Article
    context_object_name = 'posts'
    template_name = 'blog/article_archive_authors.html'
    paginate_by = 12
    allow_empty = True

    """We cannot subclass TagMixin because queryset is altered (by author), so
    the TagMixin snippets are included in get_queryset() and get() afterwards"""

    def get_queryset(self):
        qs = Article.objects.filter(author_id= self.kwargs['pk'])
        if 'tag' in self.request.GET:
            qs = qs.filter(tags__name=self.request.GET['tag'])
        return qs

    def get(self, request, *args, **kwargs):
        super(ByAuthorListView, self).get(request, *args, **kwargs)
        context = self.get_context_data()
        context['author'] = get_object_or_404( User, id = kwargs['pk'] )
        context['tags'] = Tag.objects.all()
        if 'tag' in self.request.GET:
            context['tag_filter'] = self.request.GET['tag']
        return self.render_to_response(context)

class ByUploadListView(ListView):
    model = UserUpload
    context_object_name = 'uploads'
    template_name = 'blog/uploads_by_author.html'
    paginate_by = 12
    allow_empty = True

    def get_queryset(self):
        qs = UserUpload.objects.filter(user_id= self.kwargs['pk'])
        return qs

    def get(self, request, *args, **kwargs):
        super(ByUploadListView, self).get(request, *args, **kwargs)
        context = self.get_context_data()
        context['author'] = get_object_or_404( User, id = kwargs['pk'] )
        return self.render_to_response(context)

blog/templates/blog/article_archive.html
{% extends 'blog/article_archive_tags.html' %}

{% block title %}{{ website.acro }} | Articoli{% endblock title %}
{% block article_archive %}
<h4><strong>
  Articoli di approfondimento
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
{% if is_paginated %}
<nav aria-label="Page navigation container">
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
  {% endif %}
</ul>
</nav>
{% endif %}
{% endblock article_archive %}

blog/templates/blog/article_archive_authors.html
{% extends 'blog/article_archive_tags.html' %}

{% block title %}{{ website.acro }} | Articoli di {{ author.get_full_name }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  Articoli di approfondimento di 
  {% if tag_filter %}
  <a href="/articoli/autori/{{ author.id }}/">{{ author.get_full_name }}</a>
  nella categoria: {{ tag_filter|upper }}
  {% else %}
  {{ author.get_full_name }}
  {% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
{% if is_paginated %}
<nav aria-label="Page navigation container">
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
  <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
  {% endif %}
  {% if page_obj.has_next %}
  <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
  {% endif %}
</ul>
</nav>
{% endif %}
{% endblock article_archive %}

blog/templates/blog/article_archive_day.html
{% extends 'blog/article_archive_tags.html' %}

{% block title %}{{ website.acro }} | Articoli {{ day }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  Articoli del {{ day }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_day %}
    <li><a href="/articoli/{{ previous_day|date:"Y/m/d" }}" class="page-link">&laquo; PRECEDENTE </a></li>
    {% endif %}
    {% if next_day %}
    <li><a href="/articoli/{{ next_day|date:"Y/m/d" }}" class="page-link"> SUCCESSIVO &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock article_archive %}

blog/templates/blog/article_archive_list.html
{% load fb_versions %}

{% if posts %}
<div class="card-deck">
{% for post in posts %}
<div class="card" style="margin-bottom: 20px; min-width: 18rem;">
  <div class="card-header">
    <h4 class="card-title">
    <a href="/articoli/{{ post.date|date:"Y/m/d" }}/{{ post.slug }}">
      {{ post.title }}</a></h4>
  </div>
  {% if post.get_image %}
    <img class="card-img-top" src="{% version post.get_image 'landscape' %}" alt="{{ post.intro }}">
  {% endif %}
  <div class="card-body">
    <em class="card-text">{{ post.intro }}</em>
    <ul class="list-inline">
      <li class="list-inline-item">
        {% if post.author %}
        <i class="fa fa-user" aria-hidden="true"></i>
        {{ post.author.get_full_name }}
        {% endif %}
      </li>
      <li class="list-inline-item">
        <i class="fa fa-calendar-o" aria-hidden="true"></i>
        {{ post.date|date:"d M Y" }}
      </li>
      {% if post.get_tags %}
        <li class="list-inline-item">
          <i class="fa fa-folder-open" aria-hidden="true"></i>
          {% for tag in post.get_tags %}
            {{ tag|upper }}
          {% endfor %}
        </li>
      {% endif %}
    </ul>
  </div>
</div>
{% endfor %}
</div>
{% else %}
<p>Non sono disponibili articoli</p>
{% endif %}

blog/templates/blog/article_archive_month.html
{% extends 'blog/article_archive_tags.html' %}

{% block title %}{{ website.acro }} | Articoli {{ month|date:"M-Y" }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  Articoli di {{ month|date:"M-Y" }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_month %}
    <li><a href="/articoli/{{ previous_month|date:"Y/m/" }}" class="page-link">&laquo; PRECEDENTE </a></li>
    {% endif %}
    {% if next_month %}
    <li><a href="/articoli/{{ next_month|date:"Y/m/" }}" class="page-link"> SUCCESSIVO &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock article_archive %}

blog/templates/blog/article_archive_tags.html
{% extends 'base.html' %}

{% block content %}
{% if tags %}
  <p>Filtra per categoria:
  {% for tag_item in tags %}
    {% if tag_item.name != tag_filter %}
      <a href="{{ request.path }}?tag={{ tag_item.name }}">{{ tag_item.name|upper }}</a>
    {% endif %}
  {% endfor %}
  </p>
{% endif %}
  <p><a href="{% url 'blog:post_authors' %}">Lista degli autori</a></p>
{% block article_archive %}
{% endblock article_archive %}
{% endblock content %}

blog/templates/blog/article_archive_year.html
{% extends 'blog/article_archive_tags.html' %}

{% block title %}{{ website.acro }} | Articoli {{ year|date:"Y" }}{% endblock title %}
{% block article_archive %}
<h4><strong>
  Articoli del {{ year|date:"Y" }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
{% include "blog/article_archive_list.html" %}
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock article_archive %}

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load fb_versions %}

{% block title %}{{ website.acro }} | {{ post.title }}{% endblock title %}

{% block content %}
    {% if post.carousel.render %}
      <div class="row">
        {{ post.carousel.render }}
      </div>
    {% endif %}
      <div class="row row-striped">
        <div class="col-md-2"></div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong>{{ post.title }}</strong></h3>
          <ul class="list-inline">
            {% if post.author %}
            <li class="list-inline-item">
              <i class="fa fa-user" aria-hidden="true"></i>
              {% if user.is_authenticated and post.author.is_active %}
              <a href="/contacts/?recipient={{ post.author_id }}&subject={{ post.title }}">
                {{ post.author.get_full_name }}</a>
              {% else %}
              {{ post.author.get_full_name }}
              {% endif %}
            </li>
            {% endif %}
            <li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i> {{ post.date|date:"d M Y" }}</li>
            {% if post.get_tags %}
              <li class="list-inline-item">
                <i class="fa fa-folder-open" aria-hidden="true"></i>
                {% for tag in post.get_tags %}
                  <a href="/articoli/?tag={{ tag }}">{{ tag|upper }}</a>
                {% endfor %}
              </li>
            {% endif %}
            {% if perms.blog.change_article %}
            <li class="list-inline-item">
              <i class="fa fa-pencil" aria-hidden="true"></i>
              <a href="/admin/blog/article/{{ post.id }}/change/">Modifica</a>
            </li>
            {% endif %}
          </ul>
          <p>{{ post.intro }}</p>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
          {{ post.stream.render }}
          <hr class="mb-4">
          {% if user.is_authenticated and user.profile.is_trusted %}
            <div class="row">
              <h4 id="upload-anchor"><strong>Contributi</strong></h4>
            </div>
            <div class="row">
              <a href="/articoli/contributi/?post_id={{ post.id }}">
              Aggiungi un contributo</a>
            </div>
            <hr class="mb-4">
            {% if post.get_uploads %}
            <div class="card-deck">
              {% for upload in post.get_uploads %}
                {% include 'blog/uploads.html' %}
              {% endfor %}
            </div>
            <hr class="mb-4">
            {% endif %}
          {% else %}
            <div class="row">
              Esegui il <a href="/accounts/login/?next={{ request.get_full_path }}">&nbsp;login&nbsp;</a> se vuoi aggiungere un contributo
            </div>
            <hr class="mb-4">
          {% endif %}
          <div class="row">
            <div class="col col-6 text-left">
            {% with prev=post.get_previous %}{% if prev %}
              <i class="fa fa-arrow-left" aria-hidden="true"></i>
              <a href="{{ prev.get_path }}">{{ prev.title }}</a>
            {% endif %}{% endwith %}
            </div>
            <div class="col col-6 text-right">
              {% with next=post.get_next %}{% if next %}
              <a href="{{ next.get_path }}">{{ next.title }}</a>
              <i class="fa fa-arrow-right" aria-hidden="true"></i>
              {% endif %}{% endwith %}
            </div>
          </div>
        </div>
      </div>
{% endblock content %}

blog/templates/blog/author_list.html
{% extends 'base.html' %}
{% load fb_versions %}

{% block title %}{{ website.acro }} | Autori{% endblock title %}

{% block content %}
<h4><strong>Lista degli autori</strong></h4>
<hr class="mb-4">
{% if authors %}
  {% with pass=user.is_authenticated %}
    {% for author, counts in authors.items %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          {% if author.profile.avatar %}
          <img src="{% version author.profile.get_thumb 'admin_thumbnail' %}" class="rounded-circle">
          {% endif %}<h5>{{ author.get_full_name }}</h5>
        </div>
        <div class="col-md-8">
          <p>{{ author.profile.bio|default_if_none:"Nessuna nota biografica" }}</p>
          <ul class="list-inline">
            {% if pass and counts.0 %}
              <li class="list-inline-item">
                <i class="fa fa-folder-open" aria-hidden="true"></i>
                  Numero di <a href="/articoli/autori/{{ author.id }}/">articoli</a>: {{ counts.0 }}
              </li>
            {% endif %}
            {% if pass and counts.1 %}
              <li class="list-inline-item">
                <i class="fa fa-upload" aria-hidden="true"></i>
                  Numero di <a href="/articoli/uploads/{{ author.id }}/">contributi</a>: {{ counts.1 }}
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    {% endfor %}
  {% endwith %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono autori.</p>
    </div>
{% endif %}
<hr class="mb-4">
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock content %}

blog/templates/blog/uploads.html
{% load fb_versions %}
<div class="card" style="margin-bottom: 20px; min-width: 18rem;">
    {% if upload.image %}
    <img class="card-img-top" src="{% version upload.image 'large' %}" width="100%" alt="" />
    {% endif %}
  <div class="card-body">
    <p class="card-text">{{ upload.body }}</p>
  </div>
  <div class="card-footer">
    {% if upload.user.profile.avatar %}
    <img src="{% version upload.user.profile.get_thumb 'admin_thumbnail' %}" width="32px" class="rounded-circle">
    {% endif %}
    {{ upload.user.get_full_name }}, caricato il {{ upload.date|date:"d M Y"}}
  </div>
</div>

blog/templates/blog/userupload_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ website.acro }} | Aggiungi contributo{% endblock title %}

{% block content %}
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <h4><strong>Aggiungi un contributo</strong></h4>
    <p>Ciao {{ user.get_short_name }}, inserisci qui sotto il tuo contributo e poi invia.</p>
    <form action="" method="post" class="needs-validation" enctype="multipart/form-data" novalidate>
              <div class="row">
                <div class="col-md-9 mb-3">
                  {{ form.image|as_crispy_field }}
                </div>
              </div>
              <div class="row">
                <div class="col-md-9 mb-3">
                  {{ form.body|as_crispy_field }}
                </div>
              </div>
              {% include 'users/profile_includes/button.html' %}
      {% csrf_token %}
    </form>
  </div>
</div>
{% endblock content %}