users/urls.py
from django.urls import path
from .views import (FrontLoginView, FrontLogoutView, FrontPasswordResetView,
    TemplateResetView, FrontPasswordResetConfirmView, TemplateResetDoneView,
    TemplateAccountView, FrontPasswordChangeView, FrontPasswordChangeDoneView,
    ProfileChangeView, ProfileDeleteView, TemplateDeletedView,
    ProfileChangeRegistryView, ProfileChangeAddressView, ProfileChangeCourseView,
    ProfileChangeNoCourseView, ProfileAddChildView, ProfileDeleteChildView,
    TemplateDeletedChildView, ProfileReleaseView, TemplateReleasedView)

#namespace is '/accounts/'
urlpatterns = [
    path('profile/', TemplateAccountView.as_view(),
        name='profile'),
    path('profile/<int:pk>/change/', ProfileChangeView.as_view(),
        name='profile_change'),
    path('profile/<int:pk>/change/registry/', ProfileChangeRegistryView.as_view(),
        name='profile_change_registry'),
    path('profile/<int:pk>/change/address/', ProfileChangeAddressView.as_view(),
        name='profile_change_address'),
    path('profile/<int:pk>/change/course/', ProfileChangeCourseView.as_view(),
        name='profile_change_course'),
    path('profile/<int:pk>/change/no_course/', ProfileChangeNoCourseView.as_view(),
        name='profile_change_no_course'),
    path('profile/add_child/', ProfileAddChildView.as_view(),
        name='profile_add_child'),
    path('profile/<int:pk>/delete/', ProfileDeleteView.as_view(),
        name='profile_delete'),
    path('profile/<int:pk>/delete_child/', ProfileDeleteChildView.as_view(),
        name='profile_delete_child'),
    path('profile/deleted/', TemplateDeletedView.as_view(),
        name='profile_deleted'),
    path('profile/deleted_child/', TemplateDeletedChildView.as_view(),
        name='profile_deleted_child'),
    path('profile/<int:pk>/release/', ProfileReleaseView.as_view(),
        name='profile_release'),
    path('profile/released/', TemplateReleasedView.as_view(),
        name='profile_released'),
    path('login/', FrontLoginView.as_view(),
        name='front_login'),
    path('logout/', FrontLogoutView.as_view(),
        name='front_logout'),
    path('password_reset/', FrontPasswordResetView.as_view(),
        name='front_password_reset'),
    path('password_reset/done/', TemplateResetView.as_view(),
        name='password_reset_done'),
    path('reset/<uidb64>/<token>/', FrontPasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path('reset/done/', TemplateResetDoneView.as_view(),
        name='password_reset_complete'),
    path('password_change/', FrontPasswordChangeView.as_view(),
        name='password_change'),
    path('password_change_done/', FrontPasswordChangeDoneView.as_view(),
        name='password_change_done'),
    ]

cronache/models.py
import re
from datetime import datetime

from django.conf import settings
from django.core.mail import EmailMessage
from django.db import models
from django.utils.timezone import now
from django.utils.html import format_html, strip_tags

from filebrowser.fields import FileBrowseField
from taggit.managers import TaggableManager
from streamfield.fields import StreamField

from streamblocks.models import (IndexedParagraph, CaptionedImage, Gallery,
    LandscapeGallery, DownloadableFile, LinkableList, BoxedText, EventUpgrade)
from users.models import User, Profile
from project.utils import generate_unique_slug

from .choices import *

class Location(models.Model):
    fb_image = FileBrowseField("Immagine", max_length=200,
        directory="images/locations/", extensions=[".jpg", ".png", ".jpeg", ".gif",
        ".tif", ".tiff"], null=True, blank=True)
    title = models.CharField('Titolo',
        help_text='Il nome del luogo',
        max_length = 50)
    slug = models.SlugField(max_length=50, unique=True)
    address = models.CharField('Indirizzo', max_length = 200,
        help_text = 'Via/Piazza, civico, CAP, Città',)
    gmap_link = models.URLField('Link di Google Map',
        blank= True, null=True,
        help_text="Dal menu di Google Maps seleziona 'Condividi/link', \
                   copia il link e incollalo qui",
    )
    gmap_embed = models.TextField('Incorpora Google Map',
        blank= True, null=True, max_length=500,
        help_text="Dal menu di Google Maps seleziona 'Condividi/incorpora', \
                   copia il link e incollalo qui",
    )
    body = models.TextField('Descrizione', blank= True, null=True,)
    website = models.URLField('Sito internet',
        blank= True, null=True, )
    email = models.EmailField(blank = True, null = True,
        verbose_name = 'Email',)
    phone = models.CharField(max_length = 50,
        blank = True, null = True, verbose_name = 'Telefono/i',)

    def save(self, *args, **kwargs):
        if not self.gmap_embed.startswith('http'):
            # thanks to geeksforgeeks.com! findall returns a list
            list = re.findall('http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\(\), ]|(?:%[0-9a-fA-F][0-9a-fA-F]))+', self.gmap_embed)
            if list:
                self.gmap_embed = list[0]
        if not self.slug:  # create
            self.slug = generate_unique_slug(Location, self.title)
        super(Location, self).save(*args, **kwargs)

    def get_gmap_link(self):
        if self.gmap_link:
            link = format_html('<a href="{}" class="btn" target="_blank">Mappa</a>',
                self.gmap_link)
        else:
            link = '-'
        return link
    get_gmap_link.short_description = 'Link di Google Maps'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Luogo'
        verbose_name_plural = 'Luoghi'
        ordering = ('id', )

class Event(models.Model):
    fb_image = FileBrowseField("Immagine", max_length=200,
        directory="images/events/",
        extensions=[".jpg", ".png", ".jpeg", ".gif", ".tif", ".tiff"],
        null=True, blank=True)
    carousel = StreamField(model_list=[ LandscapeGallery, ],
        null=True, blank=True, verbose_name="Galleria",
        help_text="Una sola galleria, per favore, larghezza minima immagini 2048px")
    title = models.CharField('Titolo',
        help_text="Il titolo dell'evento",
        max_length = 50)
    slug = models.SlugField(max_length=50, editable=False, null=True)
    date = models.DateTimeField('Quando', default = now)
    last_updated = models.DateTimeField(editable=False, null=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL,
        null = True, verbose_name = 'Dove', )
    intro = models.CharField('Introduzione',
        default = 'Un altro appuntamento con RP!', max_length = 100)
    stream = StreamField(model_list=[ IndexedParagraph, CaptionedImage,
        Gallery, DownloadableFile, LinkableList, BoxedText, ],
        verbose_name="Lancio")
    upgrade_stream = StreamField(model_list=[ EventUpgrade, IndexedParagraph,
        DownloadableFile, ],
        verbose_name="Aggiornamenti")
    chron_stream = StreamField(model_list=[ IndexedParagraph, CaptionedImage,
        Gallery, DownloadableFile, LinkableList, BoxedText],
        verbose_name="Cronaca")
    restr_stream = StreamField(model_list=[ IndexedParagraph, CaptionedImage,
        Gallery, DownloadableFile, LinkableList, BoxedText],
        verbose_name="Area riservata",
        help_text="Inserisci qui materiale riservato ai soci",)
    stream_search = models.TextField(editable=False, null=True)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL,
        blank= True, null=True, verbose_name = 'Responsabile')
    tags = TaggableManager(verbose_name="Categorie",
        help_text="Lista di categorie separate da virgole",
        through=None, blank=True)
    notice = models.CharField(max_length = 4, choices = NOTICE,
        blank = True, null = True, verbose_name = 'Notifica via email',
        help_text = """Invia notifica in automatico selezionando
            'Invia notifica' e salvando l'articolo.
            """)

    def get_badge_color(self):
        if self.date.date() > now().date():
            return 'success'
        elif self.date.date() < now().date():
            return 'secondary'
        else:
            return 'warning'

    def get_image(self):
        image = None
        gallery_list = self.carousel.from_json()
        if gallery_list:
            gallery = gallery_list[0]
            image = LandscapeGallery.objects.filter( id__in = gallery['id'] ).first()
        if image:
            return image.fb_image
        elif self.location.fb_image:
            return self.location.fb_image
        return

    def get_tags(self):
        return list(self.tags.names())

    def get_chronicle(self):
        if self.date.date() < datetime.today().date():
            return True
        return False

    def get_path(self):
        return '/calendario/' + self.date.strftime("%Y/%m/%d") + '/' + self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(Event, self.title)
        self.last_updated = now()
        #in tests treats stream as str instead of StreamField object
        #probably should use transaction instaed
        #but for now this patch works
        if isinstance(self.stream, str):
            from streamfield.base import StreamObject
            tmp = StreamObject( value = self.stream,
                model_list=[ IndexedParagraph, CaptionedImage,
                    Gallery, DownloadableFile, LinkableList, BoxedText ], )
            self.stream_search = strip_tags(tmp.render)
            tmp2 = StreamObject( value = self.upgrade_stream,
                model_list=[ EventUpgrade, IndexedParagraph,
                    DownloadableFile ], )
            self.stream_search += strip_tags(tmp2.render)
            tmp3 = StreamObject( value = self.chron_stream,
                model_list=[ IndexedParagraph, CaptionedImage,
                    Gallery, DownloadableFile, LinkableList, BoxedText ], )
            self.stream_search += strip_tags(tmp3.render)
            tmp4 = StreamObject( value = self.restr_stream,
                model_list=[ IndexedParagraph, CaptionedImage,
                    Gallery, DownloadableFile, LinkableList, BoxedText ], )
            self.stream_search += strip_tags(tmp4.render)
        else:
            self.stream_search = strip_tags(self.stream.render)
            self.stream_search += strip_tags(self.upgrade_stream.render)
            self.stream_search += strip_tags(self.chron_stream.render)
            self.stream_search += strip_tags(self.restr_stream.render)
        if self.notice == 'SPAM':
            message = self.title + '\n'
            message += self.intro + '\n'
            url = settings.BASE_URL + self.get_path()
            message += 'Fai click su questo link per leggerlo: ' + url + '\n'
            recipients = User.objects.filter( is_active = True, )
            #inactive users may not have profile
            recipients = recipients.filter( profile__yes_spam = True, )
            mailto = []
            for recipient in recipients:
                mailto.append(recipient.email)
            subject = f'Nuovo evento su {settings.WEBSITE_NAME}'
            email = EmailMessage(subject, message, settings.SERVER_EMAIL,
                mailto)
            email.send()
            self.notice = 'DONE'
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Evento'
        verbose_name_plural = 'Eventi'
        ordering = ('-date', )

cronache/forms.py
from django import forms
from django.forms import ModelForm
from .models import Event
from users.models import User

class EventForm(ModelForm):
    manager = forms.ModelChoiceField(label="Responsabile", required = False,
        queryset = User.objects.with_perm('cronache.add_event').order_by('last_name',
        'first_name', 'username'), )

    class Meta:
        model = Event
        fields = '__all__'

cronache/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import (ListView, DetailView, CreateView,
    TemplateView)
from django.views.generic.dates import (ArchiveIndexView, YearArchiveView,
    MonthArchiveView, DayArchiveView, )

from taggit.models import Tag

from .models import (Location, Event, )
from blog.models import UserUpload

class ListLocation(ListView):
    model = Location
    context_object_name = 'all_locations'
    paginate_by = 12

class DetailLocation(DetailView):
    model = Location
    context_object_name = 'location'
    slug_field = 'slug'

class TagMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        if 'categoria' in self.request.GET:
            context['tag_filter'] = self.request.GET['categoria']
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if 'categoria' in self.request.GET:
            qs = qs.filter(tags__name=self.request.GET['categoria'])
        return qs

class EventArchiveIndexView(TagMixin, ArchiveIndexView):
    model = Event
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    paginate_by = 12
    allow_empty = True

class EventYearArchiveView(TagMixin, YearArchiveView):
    model = Event
    make_object_list = True
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    paginate_by = 12
    year_format = '%Y'
    allow_empty = True

class EventMonthArchiveView(TagMixin, MonthArchiveView):
    model = Event
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    year_format = '%Y'
    month_format = '%m'
    allow_empty = True

class EventDayArchiveView(TagMixin, DayArchiveView):
    model = Event
    date_field = 'date'
    allow_future = True
    context_object_name = 'all_events'
    year_format = '%Y'
    month_format = '%m'
    day_format = '%d'
    allow_empty = True

class DetailEvent(DetailView):
    model = Event
    context_object_name = 'event'
    slug_field = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        uploads = UserUpload.objects.filter(event_id = self.object.id)
        context['all_uploads'] = uploads
        return context

cronache/templates/cronache/event_archive.html
{% extends 'cronache/event_archive_general.html' %}

{% block title %}RP | Calendario{% endblock title %}
{% block event_archive %}
<h4><strong>
  Appuntamenti e cronache
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
<hr class="mb-4">
{% if all_events %}
    {% for event in all_events %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <a href="/calendario/{{ event.date|date:"Y/m" }}/"><h4>{{ event.date|date:"M-Y" }}</h4></a>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong><a href="/calendario/{{ event.date|date:"Y/m/d" }}/{{ event.slug }}">{{ event.title }}</a></strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'cronache/event_list_inline.html'%}
            {% include 'cronache/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
    {% endfor %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono eventi in calendario.</p>
    </div>
{% endif %}
<hr class="mb-4">
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock event_archive %}

cronache/templates/cronache/event_archive_day.html
{% extends 'cronache/event_archive_general.html' %}

{% block title %}RP | Calendario {{ day }}{% endblock title %}
{% block event_archive %}
<h4><strong>
  Appuntamenti e cronache {{ day }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
<hr class="mb-4">
{% if all_events %}
    {% for event in all_events %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <a href="/calendario/{{ event.date|date:"Y/m" }}/"><h4>{{ event.date|date:"M-Y" }}</h4></a>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong><a href="/calendario/{{ event.date|date:"Y/m/d" }}/{{ event.slug }}">{{ event.title }}</a></strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'cronache/event_list_inline.html'%}
            {% include 'cronache/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
    {% endfor %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono eventi in calendario.</p>
    </div>
{% endif %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_day %}
    <li><a href="/calendario/{{ previous_day|date:"Y/m/d" }}" class="page-link">&laquo; PRECEDENTE </a></li>
    {% endif %}
    {% if next_day %}
    <li><a href="/calendario/{{ next_day|date:"Y/m/d" }}" class="page-link"> SUCCESSIVO &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock event_archive %}

cronache/templates/cronache/event_archive_general.html
{% extends 'base.html' %}

{% block content %}
{% if tags %}
  <p>Filtra per categoria:
  {% for tag_item in tags %}
    {% if tag_item.name == tag_filter %}
    {% else %}
      <a href="{{ request.path }}?categoria={{ tag_item.name }}">{{ tag_item.name|upper }}</a>
    {% endif %}
  {% endfor %}
  </p>
{% endif %}
{% block event_archive %}
{% endblock event_archive %}
{% endblock content %}

cronache/templates/cronache/event_archive_month.html
{% extends 'cronache/event_archive_general.html' %}

{% block title %}RP | Calendario {{ month|date:"M-Y" }}{% endblock title %}
{% block event_archive %}
<h4><strong>
  Appuntamenti e cronache {{ month|date:"M-Y" }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
<hr class="mb-4">
{% if all_events %}
    {% for event in all_events %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <h4>{{ event.date|date:"M-Y" }}</h4>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong><a href="/calendario/{{ event.date|date:"Y/m/d" }}/{{ event.slug }}">{{ event.title }}</a></strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'cronache/event_list_inline.html'%}
            {% include 'cronache/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
    {% endfor %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono eventi in calendario.</p>
    </div>
{% endif %}
<hr class="mb-4">
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if previous_month %}
    <li><a href="/calendario/{{ previous_month|date:"Y/m/" }}" class="page-link">&laquo; PRECEDENTE </a></li>
    {% endif %}
    {% if next_month %}
    <li><a href="/calendario/{{ next_month|date:"Y/m/" }}" class="page-link"> SUCCESSIVO &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endblock event_archive %}

cronache/templates/cronache/event_archive_year.html
{% extends 'cronache/event_archive_general.html' %}

{% block title %}RP | Calendario {{ year|date:"Y" }}{% endblock title %}
{% block event_archive %}
<h4><strong>
  Appuntamenti e cronache {{ year|date:"Y" }}
  {% if tag_filter %} nella categoria: {{ tag_filter|upper }}{% endif %}
</strong></h4>
<hr class="mb-4">
{% if all_events %}
    {% for event in all_events %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <a href="/calendario/{{ event.date|date:"Y/m" }}/"><h4>{{ event.date|date:"M-Y" }}</h4></a>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong><a href="/calendario/{{ event.date|date:"Y/m/d" }}/{{ event.slug }}">{{ event.title }}</a></strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'cronache/event_list_inline.html'%}
            {% include 'cronache/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
    {% endfor %}
{% else %}
    <div class="col-md-12">
        <p>Non ci sono eventi in calendario.</p>
    </div>
{% endif %}
<hr class="mb-4">
{% if is_paginated %}
  <nav aria-label="Page navigation container">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PRECEDENTI </a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> PROSSIMI &raquo;</a></li>
    {% endif %}
  </ul>
  </nav>
{% endif %}
{% endblock event_archive %}

cronache/templates/cronache/event_detail.html
{% extends 'base.html' %}

{% block title %}RP | {{ event.title }}{% endblock title %}
{% block content %}
      {% if event.carousel.render %}
        <div class="row">
          {{ event.carousel.render }}
        </div>
      {% elif event.get_image %}
        <div class="row">
          <img src="{{ event.get_image.url }}" width="100%" alt="{{ event.intro }}" />
        </div>
      {% endif %}
      <div class="row row-striped">
        <div class="col-md-2 text-center">
          <h1 class="display-4"><span class="badge badge-{{ event.get_badge_color }}">{{ event.date|date:"j" }}</span></h1>
          <a href="/calendario/{{ event.date|date:"Y/m" }}/"><h4>{{ event.date|date:"M-Y" }}</h4></a>
        </div>
        <div class="col-md-10">
          <h3 class="text-uppercase"><strong>{{ event.title }}</strong></h3>
          <p>{{ event.intro }}</p>
          <ul class="list-inline">
            {% include 'cronache/event_list_inline.html'%}
            {% include 'cronache/event_list_inline_2.html'%}
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8"
          style="margin-right: 15px; margin-left: 15px; margin-top: 15px">
        {% if event.get_chronicle %}
          <div class="row">
            <h4><strong>Cronaca</strong></h4>
          </div>
          {% if event.chron_stream.render %}
            {{ event.chron_stream.render }}
          {% else %}
          <p>Ci stiamo lavorando! intanto aggiungete qualche contributo.</p>
          {% endif %}
          <hr class="mb-4">
          {% if user.is_authenticated and user.profile.is_trusted %}
            {% if event.restr_stream.render %}
            <div class="row">
              <h4><strong>Area riservata</strong></h4>
            </div>
              {{ event.restr_stream.render }}
            <hr class="mb-4">
            {% endif %}
            <div class="row">
              <h4 id="upload-anchor"><strong>Contributi</strong></h4>
            </div>
            <div>
              <a href="/calendario/contributi/?event_id={{ event.id }}">
              Aggiungi un contributo</a>
            </div>
            {% if all_uploads %}
            <hr class="mb-4">
            <div class="card-deck">
              {% for upload in all_uploads %}
                {% include 'blog/uploads.html' %}
              {% endfor %}
            </div>
            {% endif %}
          {% else %}
            <div>
              <p>Esegui il <a href="/login/?next={{ request.get_full_path }}">&nbsp;login&nbsp;</a>
                se vuoi visitare l'area riservata ed aggiungere un contributo</p>
            </div>
          {% endif %}
          <hr class="mb-4">
        {% endif %}
          {% if event.upgrade_stream.render %}
            <div class="row">
              <h4><strong>Aggiornamenti</strong></h4>
            </div>
              {{ event.upgrade_stream.render }}
            <div class="row">
              <h4><strong>Articolo originale</strong></h4>
            </div>
          {% endif %}
            {{ event.stream.render }}
        </div>
      </div>
{% endblock content %}

cronache/templates/cronache/event_list_inline.html
<li class="list-inline-item"><i class="fa fa-calendar-o" aria-hidden="true"></i>
  {{ event.date|date:"l" }}</li>
<li class="list-inline-item"><i class="fa fa-clock-o" aria-hidden="true"></i>
  {{ event.date|date:"H:i" }}</li>
<li class="list-inline-item"><i class="fa fa-location-arrow" aria-hidden="true"></i>
  <a href="/luoghi/{{ event.location.slug }}">{{ event.location.title }}</a></li>

{% if event.manager %}
  <li class="list-inline-item">
    <i class="fa fa-user" aria-hidden="true"></i>
    {% if user.is_authenticated %}
      <a href="/contacts/?recipient={{ event.manager_id }}">
        {{ event.manager.get_full_name }}</a>
    {% else %}
      {{ event.manager.get_full_name }}
    {% endif %}
  </li>
{% endif %}

<li class="list-inline-item">
  <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
  Ultima modifica: {{ event.last_updated|date:"d M Y" }}
</li>

{% if perms.cronache.change_event %}
<li class="list-inline-item">
  <i class="fa fa-pencil" aria-hidden="true"></i>
  <a href="/admin/cronache/event/{{ event.id }}/change/">Modifica</a>
</li>
{% endif %}

cronache/templates/cronache/event_list_inline_2.html
{% if event.get_tags %}
  <li class="list-inline-item">
    <i class="fa fa-folder-open" aria-hidden="true"></i>
    {% for tag in event.get_tags %}
      <a href="/calendario/?categoria={{ tag }}">{{ tag|upper }}</a>
    {% endfor %}
  </li>
{% endif %}

{% if event.event_race.all %}
<li class="list-inline-item">
  <i class="fa fa-flag-checkered" aria-hidden="true"></i>
  {% for race in event.event_race.all %}
    <a href="{{ race.get_path }}">{{ race.title }}</a>
  {% endfor %}
</li>
{% endif %}